config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'

  get 'home', to: 'static_pages#index'

  resources :users do
    resources :ukuleles
  end

  resources :videos, only: [:index, :new, :create]
  
  namespace :api do
    namespace :v1 do
      resources :ukuleles, only: [:index, :create]
      resources :users, only: [:index]
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument_type.rb
class InstrumentType < ApplicationRecord
  validates :instrument_type, presence: true, uniqueness: true
end

app/models/ukulele.rb
class Ukulele < ApplicationRecord
  include PgSearch
  multisearchable :against => [
    :instrument_type,
    :ukulele_shape,
    :ukulele_size,
    :luthier,
    :model,
    :serial_number,
    :purchase_date,
    :body_top,
    :body_sides,
    :body_back,
    :body_neck,
    :body_fretboard,
    :body_binding,
    :tuner_type,
    :tuner_manufacture,
    :string_manufacture,
    :string_count,
    :string_tuning,
    :finish_type,
    :finish_look,
    :pickup,
    :nut_material,
    :saddle_material,
    :neck_width,
    :length_scale,
    :length_body,
    :width,
    :depth,
    :nickname
  ]

  validates :instrument_type, presence: true
  validates :ukulele_shape, presence: true
  validates :ukulele_size, presence: true
  validates :string_count, numericality: true, allow_nil: true
  validates :neck_width, numericality: true, allow_nil: true
  validates :length_scale, numericality: true, allow_nil: true
  validates :length_body, numericality: true, allow_nil: true
  validates :width, numericality: true, allow_nil: true
  validates :depth, numericality: true, allow_nil: true

  belongs_to :user

  has_many :instrument_types
  has_many :ukulele_shapes
  has_many :ukulele_sizes

  mount_uploaders :photos, UkulelePhotosUploader

  def vbulletin
    "#{self.luthier} #{self.model} #{self.ukulele_size}"
  end

  def youtube(url)
    if !url.present?
      return ""
    elsif url.include?("www.youtube.com/watch?v=")
      uid_start = url.index("=") + 1
    elsif url.include?("youtu.be/")
      uid_start = url.index("be/") + 3
    elsif url.include?("https://www.youtube.com/embed/")
      uid_start = url.index("https://www.youtube.com/embed/") + 30
    end
    url.slice(uid_start, 11)
  end
end

app/models/ukulele_shape.rb
class UkuleleShape < ApplicationRecord
  validates :ukulele_shape, presence: true, uniqueness: true
end

app/models/ukulele_size.rb
class UkuleleSize < ApplicationRecord
  validates :ukulele_size, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :ukuleles

  mount_uploader :avatar, AvatarUploader
end

app/models/video.rb
class Video < ApplicationRecord

  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

  validates :link, presence: true, format: YT_LINK_FORMAT

end

app/controllers/api/v1/ukuleles_controller.rb
class Api::V1::UkulelesController < ApplicationController
  skip_before_action :verify_authenticity_token
  # protect_from_forgery unless: -> { request.format.json? }

  def index
    # respond_to do |format|
    #   format.json do
    #     render json: { ukuleles: ukuleles }
    #   end
    # end
    @ukuleles = Ukulele.all
    render json: {ukuleles: @ukuleles}
  end

  def create
    @ukuleles = Ukulele.all
    if params[:query]
      query = params[:query]
      @found_records = PgSearch.multisearch(query)
      @ukuleles = []
      @found_records.each do |result|
        @ukuleles << Ukulele.find(result.searchable_id)
      end
      render json: { ukuleles: @ukuleles }
    else
      @ukuleles = ""
    end
  end

  private

  def ukuleles
    params.permit(:query)
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  protect_from_forgery unless: -> { request.format.json? }

  def index
    @current_user = current_user
    @ukuleles = Ukulele.where(user_id: @current_user.id)
    render json: {current_user: @current_user, events: @events }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up,
      keys: [:first_name, :last_name, :avatar, :photos]
    )
  end

  def after_sign_in_path_for(resource)
    user_ukuleles_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  
  end
end

app/controllers/ukuleles_controller.rb
class UkulelesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_uke, only: [:edit, :destroy, :update]


  def create
    @user = current_user
    @ukulele = Ukulele.create(ukulele_params)
    @ukulele.user = @user

    if @ukulele.save
      flash[:notice] = "Ukulele saved"
      redirect_to user_ukulele_path(@user, @ukulele)
    else
      flash[:alert] = "Ukulele didn't save.  Try again."
      render :new
    end
  end

  def destroy
    @ukulele.destroy
    respond_to do |format|
      format.html {
        redirect_to user_ukuleles_path(current_user),
        notice: 'Ukulele was successfully deleted.'
      }
    end
  end

  def edit
    @instrument_type = InstrumentType.all
    @ukulele_shape = UkuleleShape.all
    @ukulele_size = UkuleleSize.all
    @button = "Change ukulele"
    @user = current_user
  end

  def index
    @ukuleles = Ukulele.where(user_id: current_user)
    @vbulletin = []
    @ukuleles.each do |uke|
      @vbulletin << uke.vbulletin
    end
  end


  def new
    @ukulele = Ukulele.new
    @user = current_user
    @instrument_type = InstrumentType.all
    @ukulele_shape = UkuleleShape.all
    @ukulele_size = UkuleleSize.all
    @button = "Add a ukulele"
  end

  def show
    @ukulele = Ukulele.find(params[:id])
    @nickname = set_nickname
    @vbulletin = @ukulele.vbulletin
    @youtube = @ukulele.youtube(@ukulele.video)
  end

  def update
    @user = current_user
    respond_to do |format|
      if @ukulele.update(ukulele_params)
        format.html { redirect_to user_ukulele_path(@user, @ukulele), notice: 'Ukulele was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
  def set_uke
    @ukulele = Ukulele.find(params[:id])
  end

  def set_nickname
    if @ukulele.nickname
      @ukulele.nickname
    else
      "My Ukulele"
    end
  end

  def ukulele_params
    params.require(:ukulele).permit(
      :instrument_type,
      :ukulele_shape,
      :ukulele_size,
      :luthier,
      :model,
      :serial_number,
      :purchase_date,
      :body_top,
      :body_sides,
      :body_back,
      :body_neck,
      :body_fretboard,
      :body_binding,
      :tuner_type,
      :tuner_manufacture,
      :string_manufacture,
      :string_count,
      :string_tuning,
      :finish_type,
      :finish_look,
      :pickup,
      :nut_material,
      :saddle_material,
      :neck_width,
      :length_scale,
      :length_body,
      :width,
      :depth,
      { photos: [] },
      :nickname,
      :video
    )
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.order('created_at DESC')
  end

  def new
    @video = Video.new
  end

  def create
      binding.pry
      resource = params
      video = Yt::Video.new url: resource.link
      resource.uid = video.id
      resource.title = video.title
      resource.likes = video.like_count
      resource.dislikes = video.dislike_count
      resource.published_at = video.published_at
    # rescue Yt::Errors::NoItems
      resource.title = ''


    @video = Video.new(video_params)
    if @video.save
      flash[:success] = 'Video added!'
      redirect_to root_url
    else
      render :new
    end
  end

  private

  def video_params
    params.require(:video).permit(:link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "My Ukulele Info" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id='nav' class='row'>
      <div class="small-12 medium-6 large-6 columns text-left">
          <h1 class="title"><%= link_to "My Ukulele Info", root_path %></h1>
      </div>
      <div class="small-12 medium-6 large-6 columns small-text-left medium-text-right">
        <% if user_signed_in? %>
          <p>
            Aloha, <%= current_user.first_name %>! |
            <%= link_to "My Ukuleles", user_ukuleles_path(current_user) %> |
            <%= link_to "My account", edit_user_registration_path %> |
            <%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %>
          </p>
        <% else %>
          <p>
            <%= link_to "Register", new_user_registration_path %> |
            <%= link_to "Sign in", new_user_session_path%>
          </p>
        <% end %>
        <div data-alert class="alert-box">
          <%= notice %>
          <!-- <a href="#" class="close">&times;</a> -->
        </div>
        <div data-alert class="alert-box">
          <%= alert %>
          <!-- <a href="#" class="close">&times;</a> -->
        </div>
      </div>
      </div>
    </div>

    <%= yield %>

    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">The following errors were found while submitting the form:</h3>
    </div>

    <div class="panel-body">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_ukuleleform.html.erb
<%= form_for [@user, @ukulele] do |f| %>

<div class="field">
  <%= f.label :nickname %>
  <%= f.text_field :nickname, autofocus: true, id: 'nickname' %>
</div>

<%= field_set_tag "Basics (required)" do %>
  <div class="field">
    <%= f.label :instrument_type %>
    <%= f.select(:instrument_type, options_from_collection_for_select(@instrument_type, :instrument_type, :instrument_type)) %>
  </div>

  <div class="field">
    <%= f.label :ukulele_shape %>
    <%= f.select(:ukulele_shape, options_from_collection_for_select(@ukulele_shape, :ukulele_shape, :ukulele_shape)) %>
  </div>

  <div class="field">
    <%= f.label :ukulele_size %>
    <%= f.select(:ukulele_size, options_from_collection_for_select(@ukulele_size, :ukulele_size, :ukulele_size)) %>
  </div>
<% end %>

<%= field_set_tag "Manufacture" do %>
  <div class="field">
    <%= f.label :luthier %>
    <%= f.text_field :luthier, autofocus: true, id: 'luthier' %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model, autofocus: true, id: 'model' %>
  </div>

  <div class="field">
    <%= f.label :serial_number %>
    <%= f.text_field :serial_number, autofocus: true, step: :any, id: 'serial_number' %>
  </div>

  <div class="field">
    <%= f.label :purchase_date %>
    <%= f.date_field :purchase_date, autofocus: true, id: 'purchase_date' %>
  </div>
<% end %>

<%= field_set_tag "Materials" do %>
  <div class="field">
    <%= f.label :body_top %>
    <%= f.text_field :body_top, autofocus: true, id: 'body_top' %>
  </div>

  <div class="field">
    <%= f.label :body_sides %>
    <%= f.text_field :body_sides, autofocus: true, id: 'body_sides' %>
  </div>

  <div class="field">
    <%= f.label :body_back %>
    <%= f.text_field :body_back, autofocus: true, id: 'body_back' %>
  </div>

  <div class="field">
    <%= f.label :body_neck %>
    <%= f.text_field :body_neck, autofocus: true, id: 'body_neck' %>
  </div>

  <div class="field">
    <%= f.label :body_fretboard %>
    <%= f.text_field :body_fretboard, autofocus: true, id: 'body_fretboard' %>
  </div>

  <div class="field">
    <%= f.label :body_binding %>
    <%= f.text_field :body_binding, autofocus: true, id: 'body_binding' %>
  </div>

  <div class="field">
    <%= f.label :nut_material %>
    <%= f.text_field :nut_material, autofocus: true, id: 'nut_material' %>
  </div>

  <div class="field">
    <%= f.label :saddle_material %>
    <%= f.text_field :saddle_material, autofocus: true, id: 'saddle_material' %>
  </div>
<% end %>

<%= field_set_tag "Tuners, strings, electrics" do %>
  <div class="field">
    <%= f.label :tuner_type %>
    <%= f.text_field :tuner_type, autofocus: true, id: 'tuner_type' %>
  </div>

  <div class="field">
    <%= f.label :tuner_manufacture %>
    <%= f.text_field :tuner_manufacture, autofocus: true, id: 'tuner_manufacture' %>
  </div>

  <div class="field">
    <%= f.label :string_manufacture %>
    <%= f.text_field :string_manufacture, autofocus: true, id: 'string_manufacture' %>
  </div>

  <div class="field">
    <%= f.label :string_count %>
    <%= f.number_field :string_count, autofocus: true, step: :any, id: 'string_count' %>
  </div>

  <div class="field">
    <%= f.label :string_tuning %>
    <%= f.text_field :string_tuning, autofocus: true, id: 'string_tuning' %>
  </div>

  <div class="field">
    <%= f.label :pickup %>
    <%= f.text_field :pickup, autofocus: true, id: 'pickup' %>
  </div>
<% end %>

<%= field_set_tag "Finish" do %>
  <div class="field">
    <%= f.label :finish_type %>
    <%= f.text_field :finish_type, autofocus: true, id: 'finish_type' %>
  </div>

  <div class="field">
    <%= f.label :finish_look %>
    <%= f.text_field :finish_look, autofocus: true, id: 'finish_look' %>
  </div>
<% end %>

<%= field_set_tag "Dimensions" do %>
  <div class="field">
    <%= f.label :width %>
    <%= f.number_field :width, autofocus: true, step: :any, id: 'width' %>
  </div>

  <div class="field">
    <%= f.label :depth %>
    <%= f.number_field :depth, autofocus: true, step: :any, id: 'depth' %>
  </div>

  <div class="field">
    <%= f.label :neck_width %>
    <%= f.number_field :neck_width, autofocus: true, step: :any, id: 'neck_width' %>
  </div>

  <div class="field">
    <%= f.label :length_scale %>
    <%= f.number_field :length_scale, autofocus: true, step: :any, id: 'length_scale' %>
  </div>

  <div class="field">
    <%= f.label :length_body %>
    <%= f.number_field :length_body, autofocus: true, step: :any, id: 'length_body' %>
  </div>

<% end %>

<%= field_set_tag "Media" do %>
  <div class="field">
    <%= f.label :photos %>
    <%= f.file_field :photos, multiple: true, id: 'photos' %>
  </div>

  <div class="field">
    <%= f.label :video %>
    <%= f.url_field :video, autofocus: true, placeholder: "https://www.youtube.com/...", id: 'video' %>
  </div>

<% end %>

<div class="actions">
  <%= f.submit @button %>
  <%=  link_to "Cancel", user_ukuleles_path(current_user) %>
</div>
<% end %>

app/views/static_pages/index.html.erb
<div id="app">
</div>

app/views/ukuleles/edit.html.erb
<% content_for :title do %>
  Change a ukulele
<% end %>
<div class="row">
  <div class="small-10 medium-6 large-6 columns">
    <h1><%= @button %></h1>

    <%= render :partial => "shared/ukuleleform" %>

  </div>
</div>

app/views/ukuleles/index.html.erb
<% content_for :title do %>
  My Ukuleles
<% end %>
<div class="row">
  <div class="small-10 medium-6 large-6 columns">
    <h1>My Ukuleles</h1>
    <%=  link_to "Add a ukulele", new_user_ukulele_path(current_user) %>
    <table>
      <tbody>
      <tr>
        <th>Type</th>
        <th>Size</th>
        <th>Shape</th>
        <th>Luthier</th>
      </tr>
        <tr>
          <% @ukuleles.each do |uke| %>
          <td>
            <%= link_to uke.instrument_type.titleize, user_ukulele_path(current_user, uke.id) %>
          </td>
          <td>
            <%= link_to uke.ukulele_size.titleize, user_ukulele_path(current_user, uke.id) %>
          </td>
          <td>
            <%= link_to uke.ukulele_shape.titleize, user_ukulele_path(current_user, uke.id) %>
          </td>
          <td>
            <%= link_to uke.luthier, user_ukulele_path(current_user, uke.id) %>
          </td>
        </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <h2>Share</h2>
    <p>
      Copy and paste the code below into your profile on <a href="http://forum.ukuleleunderground.com/" target="_blank">Ukulele Underground forums.</a>
    </p>
    <button class="btn" data-clipboard-target="#markup" >
      Copy code
    </button>
    <div id="markup" class="small-12">
      <textarea id="bar" rows="<%= @ukuleles.size %>">
        [B]My Ukuleles[/B]
        <% @ukuleles.each do |uke| %>
          [URL="<%= request.base_url %><%= user_ukulele_path(current_user, uke.id) %>"]<%= uke.vbulletin %>[/URL]
        <% end %>
        [SIZE=1][I][URL="http://my-ukulele-info.heroku.com"]Powered by My Ukulele Info[/URL][/I][/SIZE]
      </textarea>
    </div>
  </div>
</div>

app/views/ukuleles/new.html.erb
<% content_for :title do %>
  Add a ukulele
<% end %>
<div class="row">
  <div class="small-10 medium-6 large-6 columns">
    <h1><%= @button %></h1>

    <%= render :partial => "shared/ukuleleform" %>

  </div>
</div>

app/views/ukuleles/show.html.erb
<% content_for :title do %>
  <%= @nickname %>
<% end %>
<div class="row">
  <div class="small-12 columns">
    <h1><%= @nickname %></h1>
    <% if current_user %>
      <%= link_to 'Change', edit_user_ukulele_path(current_user, @ukulele) %> |
      <%= link_to 'Delete', user_ukulele_path(@ukulele), method: :delete, data: { confirm: 'Are you sure?' } %> |
    <% end %>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <h2>Details</h2>
  </div>
</div>
<div class="row bigcontainer">
  <div class="small-12 medium-6 large-4 columns container">
    <h3>Basics</h3>
    <p>
      Type: <%= @ukulele.instrument_type.to_s.titleize %>
    </p>
    <p>
      Size: <%= @ukulele.ukulele_size.to_s.titleize %>
    </p>
    <p>
      Shape: <%= @ukulele.ukulele_shape.to_s.titleize %>
    </p>
  </div>
  <div class="small-12 medium-6 large-4 columns container">
    <h3>Manufacture</h3>
    <p>
      Luthier: <%= @ukulele.luthier %>
    </p>
    <p>
      Model: <%= @ukulele.model %>
    </p>
    <p>
      Serial number: <%= @ukulele.serial_number %>
    </p>
    <p>
      Purchase date:
      <% if @ukulele.purchase_date.present? %>
        <%= @ukulele.purchase_date.strftime("%m/%d/%Y") %>
      <% end %>
    </p>
  </div>
  <div class="small-12 medium-6 large-4 columns container">
    <h3>Materials</h3>
    <p>
      Body top: <%= @ukulele.body_top.to_s.titleize %>
    </p>
    <p>
      Body sides: <%= @ukulele.body_sides.to_s.titleize %>
    </p>
    <p>
      Body back: <%= @ukulele.body_back.to_s.titleize %>
    </p>
    <p>
      Body neck: <%= @ukulele.body_neck.to_s.titleize %>
    </p>
    <p>
      Body fretboard: <%= @ukulele.body_fretboard.to_s.titleize %>
    </p>
    <p>
      Body binding: <%= @ukulele.body_binding.to_s.titleize %>
    </p>
    <p>
      Nut material: <%= @ukulele.nut_material.to_s.titleize %>
    </p>
    <p>
      Saddle material: <%= @ukulele.saddle_material.to_s.titleize %>
    </p>
  </div>
  <div class="small-12 medium-6 large-4 columns container">
    <h3>Tuners, strings, electrics</h3>
    <p>
      Tuner type: <%= @ukulele.tuner_type.to_s.titleize %>
    </p>
    <p>
      Tuner manufacture: <%= @ukulele.tuner_manufacture %>
    </p>
    <p>
      String manufacture: <%= @ukulele.string_manufacture.to_s.titleize %>
    </p>
    <p>
      String count: <%= @ukulele.string_count %>
    </p>
    <p>
      String tuning: <%= @ukulele.string_tuning %>
    </p>
    <p>
      Pickup: <%= @ukulele.pickup.to_s.titleize %>
    </p>
  </div>
  <div class="small-12 medium-6 large-4 columns container">
    <h3>Finish</h3>
    <p>
      Finish type: <%= @ukulele.finish_type.to_s.titleize %>
    </p>
    <p>
      Finish look: <%= @ukulele.finish_look.to_s.titleize %>
    </p>
  </div>
  <div class="small-12 medium-6 large-4 columns container">
    <h3>Dimensions</h3>
    <p>
      Width: <%= @ukulele.width %>
    </p>
    <p>
      Depth: <%= @ukulele.depth %>
    </p>
    <p>
      Neck width: <%= @ukulele.neck_width %>
    </p>
    <p>
      Scale length: <%= @ukulele.length_scale %>
    </p>
    <p>
      Body length: <%= @ukulele.length_body %>
    </p>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <h2>Pictures</h2>
  </div>
</div>
<div class="row">
    <div class="small-12 columns">
      <% if @ukulele.photos.present? %>
        <% @ukulele.photos.each do |pic| %>
          <a class="pic" href="<%= pic.url %>" data-lightbox="ukuleles" ><img class="example-image" src="<%= pic.thumb.url %>" alt=""/></a>
        <% end %>
      <% else %>
        <p>
          This ukulele doesn't have any photos.
          <% if current_user %> <%= link_to 'Add some.', edit_user_ukulele_path(current_user, @ukulele) %><% end %>
        </p>
      <% end %>
    </div>
  </div>
</section>
</div>
<div class="row">
  <div class="small-12 columns">
    <h2>Video</h2>
    <% if @youtube.present? %>
      <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @youtube %>" frameborder="0" allowfullscreen></iframe>
    <% else %>
      <p>
        This ukulele doesn't have a video.
        <% if current_user %> <%= link_to 'Add one.', edit_user_ukulele_path(current_user, @ukulele) %><% end %>
      </p>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <h2>Share</h2>
    <p>
      Copy and paste the code below into your profile on <a href="http://forum.ukuleleunderground.com/" target="_blank">Ukulele Underground forums.</a>
    </p>
    <button class="btn" data-clipboard-target="#markup" >
      Copy code
    </button>
    <div id="markup" class="small-12">
      <textarea id="bar" rows="4">
        [B]My Ukuleles[/B]
        [URL="<%= request.original_url %>"]<%= @vbulletin %>[/URL]
        [SIZE=1][I][URL="http://my-ukulele-info.heroku.com"]Powered by My Ukulele Info[/URL][/I][/SIZE]
      </textarea>
    </div>
  </div>
</div>

app/views/videos/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Share your videos with the world!</h1>
    <p>Click the button below to share your video from YouTube.</p>
    <p>
      <%= link_to 'Add video now!', new_video_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>
</div>

<% if @videos.any? %>
  <div class="container">
    <h1>Latest videos</h1>
    <div id="player-wrapper"></div>
    <% @videos.in_groups_of(3) do |group| %>
      <div class="row">
        <% group.each do |video| %>
          <% if video %>
            <div class="col-md-4">
              <div class="yt_video thumbnail">
                <%= link_to image_tag("https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg", alt: video.title,
                                      class: 'img-rounded'),
                            "https://www.youtube.com/watch?v=#{video.uid}", target: '_blank' %>
                <div class="caption">
                  <h5><%= video.title %></h5>
                  <p>Published at <%= video.published_at.strftime('%-d %B %Y %H:%M:%S') %></p>
                  <p>
                    <span class="glyphicon glyphicon glyphicon-thumbs-up"></span> <%= video.likes %>
                    <span class="glyphicon glyphicon glyphicon-thumbs-down"></span> <%= video.dislikes %>
                  </p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/videos/new.html.erb
<div class="container">
  <h1>New video</h1>

  <%= form_for @video do |f| %>
    <%= render 'shared/errors', object: @video %>

    <div class="form-group">
      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control', required: true %>
      <span class="help-block">A link to the video on YouTube.</span>
    </div>

    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>